
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RentACar.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Araba
{

    public int arabaId { get; set; }

    public string arabaMarka { get; set; }

    public string arabaModel { get; set; }

    public string arabaRenk { get; set; }

    public string arabaKasaTipi { get; set; }

    public string arabaYakit { get; set; }

    public string arabaKm { get; set; }

    public string arabaGorsel { get; set; }

    public decimal arabaFiyat { get; set; }

    public int arabaKategoriId { get; set; }

    public string arabaKodu { get; set; }



    public virtual Kategori Kategori { get; set; }

}

}
