
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RentACar.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Kullanici
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Kullanici()
    {

        this.Mesajlar = new HashSet<Mesajlar>();

        this.Mesajlar1 = new HashSet<Mesajlar>();

    }


    public int kullaniciId { get; set; }

    public string kullaniciAdSoyad { get; set; }

    public string kullaniciTel { get; set; }

    public string kullaniciMail { get; set; }

    public string kullaniciParola { get; set; }

    public string kullaniciYetki { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Mesajlar> Mesajlar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Mesajlar> Mesajlar1 { get; set; }

}

}
