

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RentACar.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class RentACarDbEntities1 : DbContext
{
    public RentACarDbEntities1()
        : base("name=RentACarDbEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Araba> Araba { get; set; }

    public virtual DbSet<Kategori> Kategori { get; set; }

    public virtual DbSet<Kullanici> Kullanici { get; set; }

    public virtual DbSet<Mesajlar> Mesajlar { get; set; }

}

}

